### ISSUE TITLE
login/signup checklist

### ISSUE THREAD

**Issue by Dayeon0820** [likelion-hackton/frontend#1]
-login signup CSS
- [ ] alert -> input에 바로 메시지 보이게
- [ ] 인증번호 전송 완료 표시( alert-> gif)
- [ ] 뒤에 체크무늬 배경
- [x] 레이아웃 깨지는거 수정
- login signup 기능
- [ ] 비밀번호 찾기, 이메일 중복 검사
- [x] 오류 메시지 종류 별로 나누기(명세서 확인)
- [ ] 비밀번호 제한 낮추기

**Comment by dani0910** [comment]
alert창 말고 모듈창으로 띄우기
