### ISSUE TITLE
home - class application checklist

### ISSUE THREAD

**Issue by dani0910** [likelion-hackton/frontend#10]
1. 신청 페이지
*ui
- [ ] 리뷰 페이지 연결
- [ ] html 구조 및 레이아웃
- [ ] 전체 css
- [ ] header, footer 제외하고 스크롤 걸기

*기능
- [ ] 라우터 연결
- [ ] api 연동
- [ ] 데이터 값 넣기

2. 신청 디테일 페이지
*ui
- [ ] html 구조 및 레이아웃 
- [ ] 캘린더 불러오기
- [ ] 캘린더 css 
- [ ] 캘린더 현재 날짜 표시 css 변경
- [ ] 토요일 글씨 파란색 or 검정색으로 변경
- [ ] 날짜 click 됐을 때 시간 선택 칸 만들기

*기능
- [ ] 신청 인원 수 버튼 onclick 이벤트 걸기
- [ ] 캘린더 날짜 선택 onclick 이벤트
- [ ] 라우터 연결

**Comment by dani0910** [comment]
수정사항 - 캘린더 반응형 크기 설정

**Comment by dani0910** [comment]
수정사항 - 캘린더 정규일 때 망가짐
