### ISSUE TITLE
search checklist

### ISSUE THREAD

**Issue by dani0910** [likelion-hackton/frontend#11]
- [ ] 최근 검색 기능
- [ ] 인기 검색어 api 호출
- [ ] 검색어 정렬  (정렬 기준이 ..????)
