### ISSUE TITLE
home checklist

### ISSUE THREAD

**Issue by dani0910** [likelion-hackton/frontend#2]
[홈 메인 페이지]

- [x] navbar ui
- [x] navbar url 연결
- [x]  클래스 유형
- [x] 배너 라이브러리 불러오기
- [ ] 인기 클래스 api 연동
- [x] 클래스 유형 별 클릭 시 해당 클래스 유형으로 클래스 목록 기본 설정 연결
- [x] 카테고리도 똑같이

**Comment by dani0910** [comment]
구조 다시 만지다가 css nav바 반응형일 때 망가졌음 고져야함
