### ISSUE TITLE
map checklist

### ISSUE THREAD

**Issue by dani0910** [likelion-hackton/frontend#3]
- [x] 카카오 map 앱 등록, 키 받아오기
(js 앱 키 : 31ab0c2dde1e7c5f97a4aba8000bfd13)
- [x] map 불러오기
- [x] 현재 위치로 중심좌표 불러오기
- [x] 마커 등록
- [x] 마커 이벤트 설정 - 해당 클래스 상세 설명 모달창
- [x] api 연동해서 클래스 값 불러오기
- [x] 상세 페이지로 이동 라우트 연결 (*클래스 등록이 되어야함)
- [ ] 로딩 만들기
- [ ] 마커 인포 div css (시간되면)

- [ ] 배포 후 플랫폼 사이트 도메인 등록하기 (ip주소 도메인 주소로 변환 필요함)

++ 
- [ ] 지역선택
