### ISSUE TITLE
profile checklist

### ISSUE THREAD

**Issue by Dayeon0820** [likelion-hackton/frontend#4]
- [ ] 기본 프로필 이미지 저장하기
- [ ] 프로필 조회, 수정 api 연결
- [ ] 사용자 타입별로 다른 ui 랜더링하기
- [ ]개최자용 ui 구성
- [ ] 클래스 생성 ui
- [ ] 클래스 생성 api 연결
- [ ] 로그아웃 작동하는지 확인
