### ISSUE TITLE
home - class_list checklist

### ISSUE THREAD

**Issue by dani0910** [likelion-hackton/frontend#7]
*ui 레이아웃
- [ ] 헤더 -클래스 유형 select 
- [ ] 메인 페이지 스크롤 
(헤더, 네브바 고정해둔거 fixed로 바꿔야함 -  fixed일 때 화면 배율에 따라 반응형 안먹는거 해결하기)
- [ ] 전체 ui 레이아웃 및 css

* 기능
- [ ] 클래스 유형, 카테고리 별 선택 들어갔을 때 해당 클래스 목록만 띄우기
- [ ] 라우터 연결
- [ ] 등록된 클래스 목록 불러오기 (api 필요)
