### ISSUE TITLE
create lecture checklist

### ISSUE THREAD

**Issue by Dayeon0820** [likelion-hackton/frontend#9]
- [ ] 주소 검색 라이브러리 불러와서 검증된 주소만 넘기기
- [ ] api수정되면 전체 점검하기
- [ ] 정규 클래스 생성 만들기(api 수정 후)
